version: "3.9"

services:
  backend:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  migrate:
    build:
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    command: sh -c "python ./manage.py migrate"

  bot:
    build:
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    command: sh -c "python ./manage.py runbot"

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: