version: "3.9"

services:
  backend:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./db.sqlite3:/app/db.sqlite3

  bot:
    build:
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    command: sh -c "python ./manage.py runbot"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3