# Generated by Django 4.2.3 on 2023-08-08 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя элемента')),
                ('description', models.TextField(blank=True, verbose_name='Описание элемента')),
                ('priority', models.SmallIntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], default=1, verbose_name='Приоритет')),
                ('count_fact', models.IntegerField(default=1, verbose_name='Количество факт')),
                ('count_need', models.IntegerField(default=1, verbose_name='Количество необходимо')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
        migrations.CreateModel(
            name='IndustrialUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название установки')),
            ],
            options={
                'verbose_name': 'Установка',
                'verbose_name_plural': 'Установки',
            },
        ),
        migrations.CreateModel(
            name='VixDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fix', models.DateTimeField(auto_now_add=True, verbose_name='Дата ремонта')),
                ('description', models.TextField(verbose_name='Описание ремонта')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='machinery.element', verbose_name='Элемент')),
            ],
            options={
                'verbose_name': 'Дата ремонта',
                'verbose_name_plural': 'Даты ремонта',
            },
        ),
        migrations.CreateModel(
            name='MachineNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название узла')),
                ('industial_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industial_units', to='machinery.industrialunit', verbose_name='Установка')),
            ],
            options={
                'verbose_name': 'Узел установки',
                'verbose_name_plural': 'Узлы установки',
            },
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название оборудования')),
                ('machine_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_nodes', to='machinery.machinenode', verbose_name='Узел установки')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.AddField(
            model_name='element',
            name='hardware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardwares', to='machinery.hardware', verbose_name='оборудование'),
        ),
        migrations.AddConstraint(
            model_name='machinenode',
            constraint=models.UniqueConstraint(fields=('name', 'industial_unit'), name='unical_mach_node'),
        ),
        migrations.AddConstraint(
            model_name='hardware',
            constraint=models.UniqueConstraint(fields=('name', 'machine_node'), name='unical_hardware'),
        ),
        migrations.AddConstraint(
            model_name='element',
            constraint=models.UniqueConstraint(fields=('name', 'hardware'), name='unical_element'),
        ),
    ]
