# Generated by Django 4.2.3 on 2023-07-27 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название оборудования')),
                ('machine_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_nodes', to='machinery.machine_node', verbose_name='Узел установки')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя элемента')),
                ('description', models.TextField(verbose_name='Описание элемента')),
                ('priority', models.SmallIntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], default=1, verbose_name='Приоритет')),
                ('count_fact', models.IntegerField(verbose_name='Количество факт')),
                ('count_need', models.IntegerField(verbose_name='Количество необходимо')),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardwares', to='machinery.hardware', verbose_name='оборудование')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
    ]
