# Generated by Django 4.2.3 on 2023-07-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('login', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='login name')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
            ],
            options={
                'verbose_name': 'Tg_user',
                'verbose_name_plural': 'Tg_users',
            },
        ),
    ]
