# Generated by Django 4.2.3 on 2023-08-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='tg_login',
            field=models.BigIntegerField(blank=True, db_index=True, verbose_name='login_tg_bot'),
        ),
    ]
