# Generated by Django 4.2.3 on 2023-08-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0004_alter_tguser_tg_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='tg_login',
            field=models.BigIntegerField(blank=True, verbose_name='Телеграм логин'),
        ),
    ]
