name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
    environment: env_mahine
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ vars.DEBUG }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
      PER_PAGE: ${{ vars.PER_PAGE }}
    steps:
    - uses: actions/checkout@v3
    - name: build .env
      run: |
        cat env-ci | envsubst > .env
    - name: clone on machine
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_SSH }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "."
        target: app/
    - name: run docker compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_SSH }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          sudo docker compose up --build -d


