name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
    environment: env_mahine
    steps:
    - uses: actions/checkout@v3
    - name: build .env
      run: |
        cat env-ci | envsubst > .env
    - name: clone on machine
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_SSH }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "."
        target: app/


